### ISSUE TITLE
Cylindrical Wind Tunnel for multiple Pedestrian Wind Comfort analysis.

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-tools/butterfly#192]
Hi @chriswmackey , I have been testing the Pedestrian Wind Comfort component of Ladybug based on the Lawson Comfort Criteria. It's a great one for the englishmen.

1. With the intention to compute a series of 18 simulations (1 every 20degress), would there be a way to benefit from a cylindrical wind tunnel in order to avoid the meshing at every iteration?
@TheodoreGalanos  I believe you had mentionned this automation case here [163](https://github.com/ladybug-analysis-tools/butterfly/issues/163) .

2. Once the cases are computed, I would be able to load all of them and plug the branches onto the _windFactor input of thePedestrian Wind Comfort component.
As the Lawson CC is based on the probability of occurence of the winds, I am not sure if the component addresses a factor to weight the values relative to the prevailing winds.
How does the component attributes the respective directions of the CFD results plugged into _windFactor? Should the northCfd_ input the wind direction of the simulation?

Kind Regards,
Olivier

**Comment by TheodoreGalanos** [comment]
Hi @DambronOlivier That is a good question. I am aware of people meshing these cases with cylindrical meshes but I have not tried it myself yet. I would guess the best way to do it is as an internal case where the cylinder is the 'room' in a sense. Making this work actually makes the post processing much much faster (pre-processing should take the same time since BF has made it easy already), so it is actually in my to-do list. But that's a slooow moving list :)

I remember reading in an article (I'll see if I can find it later) that the extent of the circular inlet/outlet surfaces should be around 120-150 degrees.

Kind regards,
Theodore.

**Comment by stgeorges** [comment]
Hi @DambronOlivier ,

I have just seen this question, even though it has been closed long time ago. My apologies for not replying on time. Unless I am not tagged in the issue, I rarely remember to check the new opened issues.

I assume you already found a solution for second question, but just for the sake of others in case they have the same.

"_windFactor" input should accept windfactors per each cardinal direction, sorted by branches.
For example the first branch should contain wind factors for your cardinal direction 0. Regardless of where the North direction of your model is located at in your CFD application!!
Then the second branch would contain wind factors for the second cardinal direction. Let's say for 20 degrees, of maybe you picked 15, or 30. Then the third branch should contain wind factors for the third cardinal direction (40, or maybe 30, or 60 degrees) and so on.
In case your CFD application does not provide wind factors (which Butterfly does, but in case you ever use any other CFD software), you can get them by dividing the cfd wind speeds you got at height of 1.75 or 1.5m by annual wind speed calculated from the .epw file (wind speed at 10 meters height). And you do this for each cardinal direction cfd values.

northCfd_ should only be used as a reference to the North direction of the model for which CFD simulations have been performed.
So it can be that in Butterfly you rotated your model by 90 degrees so that the North direction is located towards the +X axis. But in Rhino you have the North direction pointing towards the +Y axis. In that case you would set the "northCfd_" to 90, and "north_" input to 0.

There is an example file ("pedestrianWindComfort_component.gh" from dropbox.com link) mentioned in [this post](https://github.com/mostaphaRoudsari/ladybug/issues/266#issue-161709323), showing how wind factors for each cardinal direction should be added to the "_windFactor" input.

Sorry once again for not seeing the question, and please reply back in case I didn't provide a full answer.

Kind regards,
Djordje
