### ISSUE TITLE
Multigrading on wind direction referential.

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-tools/butterfly#212]
Hi @mostaphaRoudsari ,

When rotating the wind direction, although the wind tunnel rotates accordingly, it seems that the Multi-gradings remain on the world XYZ .
![capture](https://cloud.githubusercontent.com/assets/21184323/24248521/b8e4e8f0-0fc7-11e7-8915-9c16ba36beba.jpg)

Would it cause any issues if the referential of the gradings were set following the wind direction?

Kind Regards,
Olivier

**Comment by thinklikeanarchitect** [comment]
I advise you to rotate the geometry according to wind direction, in my opinion thats the easiest way unless you have used cylindirical comp. domain.

**Comment by DambronOlivier** [comment]
Hi @thinklikeanarchitect ,
Thanks.
Rotating the geometry and the test surface will require me to rotate all the Solution vectors backwards so as to compare the results. I was hoping to find a more direct method.

A cylindrical computational domain could be generated such as an indoor case within a cylinder?  In this case, generating a wind tunnel with the adequate leeward size to account for all the wind directions would be much larger and computationally big. Am I correct in the way I imagining it?

Olivier

**Comment by TheodoreGalanos** [comment]
@DambronOlivier I don't think there is an error here. The multi-grading is applied on a vector basis (x, y, and z). Rotating your wind tunnel does not change the vectors and  their direction.

The quickest solution would be for you to swap X and Y multi grading at the grading component when you rotate your wind tunnel.

Rotating the geometry is also an option as @thinklikeanarchitect suggests. I usually find that a more efficient method since it requires less preprocessing (all geometries can work with the same blockmesh properties more or less). And with the GH native components importing and rotating the mesh points is not that difficult.

Regarding the cylindrical domain, yes that is correct. It would oppose an equal distance (it's a circle after all) and that distance should be the maximum value. That means a large computational domain (in some cases quite large depending on the context) with less post-processing time. Additionally, there still needs to be an inlet, outlet, and side patches, which need to be rotated, which means re-meshing.

If you want my opinion, post-processing is not really the issue. The time spent on it, especially if you develop some crafty GH definitions for your standard cases, is very small compared to either the additional running time for a larger domain and/or the additional pre-processing/meshing time.

That said, I do have it on my to-do list to try a cylindrical domain. Will let everyone know if I manage to go through it.

Hope this helps.

Kind regards,
Theodore.

**Comment by thinklikeanarchitect** [comment]
If you dont want to mesh again and again every time and want to use rectangular domain, then for different wind directions (e.g. 45 degree from north) you have to define two inlets and two outlets at the same time.

**Comment by thinklikeanarchitect** [comment]
As to multigrading, yours seems not accurate in my opinion for both cases. At first the finer mesh do not begin at inlet and then goes to coarse mesh at outlet. On the contrary, there should be grading taking the target building as starting point for finer mesh.

**Comment by thinklikeanarchitect** [comment]
[arch.inst.japan cfd guidelines.pdf](https://github.com/ladybug-tools/butterfly/files/864903/arch.inst.japan.cfd.guidelines.pdf)

**Comment by DambronOlivier** [comment]
Thank you very much both.

Kind Regards,
Olivier

**Comment by DambronOlivier** [comment]
@thinklikeanarchitect 
![capture](https://cloud.githubusercontent.com/assets/21184323/24274907/961962e0-1023-11e7-975d-095408292018.PNG)

Would this be more appropriate? I was aiming for 1:1 ratio around the geometries.

**Comment by thinklikeanarchitect** [comment]
It seems good now:)

**Comment by TheodoreGalanos** [comment]
@DambronOlivier The leeward side looks ok. I would increase the windward side cell count, that jump looks like it's 2x, your maximum should be around 1.2. Maybe 2-3 more cells on windward.

**Comment by DambronOlivier** [comment]
I have managed to compute 12 different wind directions by rotating the geometry. Convergence times varied for each cases, although all converged.

With regards to the postprocessing to restore the relative vector directions, I rotated backwards  and respectively to the wind directions each wind vector with the testPoints as respective centres. 

Thanks again to both for the guidance. 
I think we can close this now.

Kind Regards,
Olivier
