### ISSUE TITLE
#220 How to make a simultaneous interior and exterior wind analysis?

### ISSUE THREAD

**Issue by Elarqitecto68** [ladybug-tools/butterfly#226]
Hi, I have a grasshopper designed tower, on which I have to analyze both interior and exterior windflow in order to optimize the mass and at the same time define the best possible points to locate micro wind turbine. Now I want to know how can these two analysis be unified?  And what parameters make the appropriate link between them?

**Comment by TheodoreGalanos** [comment]
Hi @Elarqitecto68 

Your starting point should always be the aspect of building performance you want to assess. What is exactly the parameter for interior spaces in this study?

In general, to simultaneously assess interior and exterior you would model both outside (building and context) and inside (the spaces, or a subset of spaces, you want to assess). In practical terms, it would amount to smth like modeling one floor of the building in Rhino, leaving the windows (if NV is the parameter) open in order to allow both meshing and wind flow within the spaces.

Hope this helps.

Kind regards,
Theodore.

**Comment by Elarqitecto68** [comment]
Hi @TheodoreGalanos 
Thanks for your attention
How does the building performance comes into the process of analyzing? what's its role?
In fact, I have a double skin facade building, and the only matter that should be involved in the analysis, is the airflow around the building and between the two skins. the facade will have several parametrical designed opening which let the air in, by these properties, do I still have to build all inside parts of the building or just the openings are sufficient?

**Comment by TheodoreGalanos** [comment]
Hi @Elarqitecto68 

I think you answered your own question. If the study is focusing on how the air flows between the two skins, and the building is not genereally NV, then you do not need the indoor spaces of the building. 

That said, I would suggest you start with a much much simpler mesh for your case. Try isolating a very small part of the double skin facade, put it in a very refined and very small wind tunnel (outdoor case), something like 0.25 by 0.25m. Refine it to a point that all salient detail is captured. Then blow some wind and see how it behaves. 

The reason for this is that if you are assessing a double skin facade, using an urban model, then your cell count is going to be extremely high in order to get the 0.1m detail in a one km wind tunnel. That's a difficult mesh. The independent facade mesh will allow you to explore and find the proper refinement for it.

Good luck!

Kind regards,
Theodore.

**Comment by Elarqitecto68** [comment]
Hi @TheodoreGalanos 
Thanks alot.
