### ISSUE TITLE
Utility of employing multi-threading (multiple processors)

### ISSUE THREAD

**Issue by sariths** [ladybug-tools/butterfly#249]
Hi @TheodoreGalanos  and @mostaphaRoudsari, 

Is there any clear idea on how the availability on number of processors affects the time taken for a simulation to converge/complete?  

I am yet to run a butterfly simulation, however, the firm that I work for is considering investing in cloud-based resources. I am wondering, if there would be a proportional benefit in renting higher number of processors. In Radiance, except for the preprocessing and post-processing part, the simulation time is almost inversely proportional to the number of processors. Does something similar hold in the case of OpenFoam?

**Comment by TheodoreGalanos** [comment]
Hi @sariths,

Due to the iterative nature of the CFD simulations the time is certainly not inversely proportional to the number of processors. At every time step, results need to be communicated between different processors. In large systems, this tends to be a significant part of computational load.

Of course, more processors will help speed up the studies in a good system. I am not sure about a precise number but I've seen some rules of thumb ranging from 50k cells to 250k cells as the minimum number per processor. Below such numbers people had found that performance actually decreases.

I have done very few tests in cloud computing, where I was a bit disappointed. This was not a CFD problem however but more so a hardware problem of the cloud computer I chose. Apart from allowing me to run larger cases, I did not see a big speed boost with older generation servers. Even at these low prices that an AWS gives, I would still need 2-3 days of running to converge a case which made costs a bit too high for my liking. I have yet to try on a top of the line, memory optimized one though.

It might be, that for CFD specifically, an investment on a very good server is worth it. But it really depends on the simulation load you have, electricity power, even currency.

Hope this helps.

Kind regards,
Theodore.

**Comment by sariths** [comment]
Hi @TheodoreGalanos ,

Thanks a lot for your insights! It would have taken me several months of trial and error to figure this out. When you've run your simulations on the cloud, are you running directly on the Linux system (unlike the docker-based system that we employ for butterfly)?

Sarith

**Comment by mostaphaRoudsari** [comment]
@sariths check this link: https://cfd.direct/cloud/

**Comment by mostaphaRoudsari** [comment]
@sariths should we close this issue?

**Comment by mostaphaRoudsari** [comment]
Closing this issue for now. Feel free to reopen if you want to discuss this more.
