### ISSUE TITLE
Issues with BlockMesh 

### ISSUE THREAD

**Issue by ldevivo** [ladybug-tools/butterfly#261]
Hello I am trying to run the first example of butterfly 01_0_outdoor_airflow and I am having trouble getting the blockMesh function to run. The error reads like this:

1. Solution exception:Failed to find container id.Do you have the OpenFOAM container running?
You can initiate OpenFOAM container by running start_OF.bat:
C:\Program Files (x86)\ESI\OpenFOAM\1612\\Windows\Scripts\start_OF.bat

I have read some of the post online and tried to fix the bug but so far no luck. I have run the docker and the OpeanFOAM as admin they are both running when I try to run the grasshopper function. I have installed and uninstalled the programs more than once. My user name is one word with no spaces. 

Please could you assist me 

Thanks

**Comment by mostaphaRoudsari** [comment]
@ldevivo what is the version of OpenFOAM that you have installed? Did you install version 1612 or 1706? If the username is set correctly and OpenFOAM also runs fine then it's most probably because you have installed the newer version.
If that is the case update butterfly installation using the update component and it should work fine with the newer version of OpenFOAM.
