### ISSUE TITLE
Snappy hex mesh 

### ISSUE THREAD

**Issue by lamlvo** [ladybug-tools/butterfly#262]
Hi,
I'm doing simulation for a house that kind of complex plan (with wind from SE (45 degree) so I have to turn on snap option in snappyhexmesh component)
I ran the butterfly without error. But when I use the paraview to check the mesh. The mesh quality is not good as I expected.
I tried many input parametres in BF geometry , block mesh, snappy mesh but I haven't received the good quality (the boundary lines of the door, windoor, wall are not straight, the shape looks weird).
When I kept the wind direction  parallel (or perpendicular ) with the edge of the house it worked really well. 
Could you help me solve this issue?
Thank you,
![snappymesh](https://user-images.githubusercontent.com/30365572/28906849-9fc7578c-7844-11e7-9f8f-270301f5ca2c.PNG)
![wind](https://user-images.githubusercontent.com/30365572/28906751-c712ceee-7843-11e7-8bb9-ca22d9254e37.PNG)
[SEwind_V2_Fullopen_Veticaltest.zip](https://github.com/ladybug-tools/butterfly/files/1196067/SEwind_V2_Fullopen_Veticaltest.zip)

**Comment by Zarisu** [comment]
Hi @lamlvo,
 
As @TheodoreGalanos says it's a mesh refinement issue. However, it is also a mesh setting issue. Therefore, I would recommend that you also change some of the mesh settings. I have had success with the following settings for complex geometries:

![mesh_settings](https://user-images.githubusercontent.com/23387793/28911719-c796df7a-7831-11e7-929b-08e508eaabd8.png)

You can change the mesh settings by writting your own settings and connecting it to 'additionalParameters_' in the 'snappyHexMeshDict' component.
 
Hope this can help, otherwise let me know :)

Best Regards Zarisu

**Comment by Zarisu** [comment]
Hi @lamlvo,

As @TheodoreGalanos says it's a mesh refinement issue. However, it is also a mesh setting issue. Therefore, I would recommend that you also change some of the mesh settings. I have had success with the following settings for complex geometries:

![mesh_settings](https://user-images.githubusercontent.com/23387793/28911867-432e0136-7832-11e7-9795-01e05bb26f5d.png)
Please notice that you can ignore the addLayersControls.

You can change the mesh settings by writting your own settings and connecting it to 'additionalParameters_' in the 'snappyHexMeshDict' component.

Hope this can help, otherwise let me know :)

Best Regards Zarisu

**Comment by Zarisu** [comment]
Hi @lamlvo,

As @TheodoreGalanos says it's a mesh refinement issue. However, it is also a mesh setting issue. Therefore, I would recommend that you also change some of the mesh settings. I have had success with the following settings for complex geometries:

![mesh_settings](https://user-images.githubusercontent.com/23387793/28911928-6e797032-7832-11e7-9180-b09a9ccbab46.png)
Notice that this is a self made component, so dont spent time searching for it ;) Furthermore, notice that you can ignore the addLayersControls.

You can change the mesh settings by writting your own settings and connecting it to 'additionalParameters_' in the 'snappyHexMeshDict' component.

Hope this can help, otherwise let me know :)

Best Regards Zarisu

**Comment by TheodoreGalanos** [comment]
@Zarisu Thanks for sharing, interesting approach to make your own component, quite nice! Interested to hear how long snapping takes with 15 feature snap iterations though!

Most of the settings feel good to me. Low tolerance means snapping easier/more often. I think you can safely increase, by alot, the solveIter value since it's the least computational intensive. Feature angle is really not clear how much impact it has. I've tried quite a few values and previewing the feature lines in paraview, in (usual) building geometries it doesn't seem to have a big effect. I would put it a bit more than 90 I think.

Concerning the globalCells of course this is the most case sensitive value. This is smth I failed to mention before @lamlvo 

When you wish to increase refinement in surfaces it is almost always necessary to increase your global cells. If you do not, the usual scenario is that your refinement stops much earlier (i.e. smaller level) than what you defined, giving you practically the same mesh.

**Comment by lamlvo** [comment]
Thank you @TheodoreGalanos  and @Zarisu Zarisu for your advise,
I'll apply in my model to check them. 

Best,

**Comment by lamlvo** [comment]
Hi Zarisu,
I try your code. The density of the mesh  is really high for all model. But I think it just need dense near the edge to correct the model. 
The second thing is snappy hex mesh just did mesh only for the building.
In paraview, It only show the buiding mesh, no mesh for wind tunnel and contexts.
Do I have to change something? Or did I did something wrong?

Thank you @Zarisu ,

**Comment by mostaphaRoudsari** [comment]
@lamlvo since the original question is replied I'm closing this issue. Feel free to open a new issue for the visualization question.

@Zarisu thank you for sharing the insight. Is the component something that you think can be shared with public? And if so should we add it to butterfly?
