### ISSUE TITLE
problem in running OpenFOAM_Start

### ISSUE THREAD

**Issue by soheilslm** [ladybug-tools/butterfly#264]
Hello Mostapha
I followed the instruction of installing as your video
running OF_Env_Create as Administrator and it was ok according to the video
running OpenFOAM_Start as Administrator and I saw this error:
![untitled](https://user-images.githubusercontent.com/23275633/28994900-010ba4de-79ef-11e7-944c-600cf1db5968.jpg)
what should I do?

**Comment by TheodoreGalanos** [comment]
Hi @soheilslm Thanks for testing Butterfly. I don't think we are ready for the 1706 version yet, try installing the previous OF installation and let us know if that works.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@soheilslm,

This means the OpenFOAM 1706 is not installed correctly. I had the same issue when I installed OpenFOAM today. You need to manually load the image by following the instruction [here](https://github.com/ladybug-tools/butterfly/wiki/Windows-10-Installation-Notes#installing-openfoam-on-a-pc-using-windows-10). 

Also since you're using version 1706 you need to update your butterfly installation.
