### ISSUE TITLE
I can't stalling butterfly in gasshopper

### ISSUE THREAD

**Issue by hoganbao** [ladybug-tools/butterfly#306]
Hi, i already have installing the python,and ghpython, but it still not working.
<img width="344" alt="2" src="https://user-images.githubusercontent.com/34123387/33421282-7f0dc4d0-d5ec-11e7-8538-b5d3aa063f89.PNG">
<img width="898" alt="default" src="https://user-images.githubusercontent.com/34123387/33421285-82e530c0-d5ec-11e7-958d-47cab31902df.PNG">

**Comment by gamemakerh** [comment]
I had same problem. If I remember correctly you should put all files "manually" then. run this block and then  delete  butterfly  files and then run this block again. 

I  think this is because you have win  10 ( I guess) and some permissions are fucket up.

just put everythink in C:\Users\YOU\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly

then run this block and check is compreset packages apear in this folder. 
delete .rar's and butterfly and butterfly_grasshopper folder. unload grasshopper. load grasshopper and run this block again. 

and everything should be fine. 

As I said. I have no idea why this happened to me, but I used this technique.

**Comment by hoganbao** [comment]
@gamemakerh Hi，thanks for your advice. I'm really sorry to have your time , but can you show me some diagrams . I try it and it's still not work, and i'm not sure i was understand this paragragh you said
（then run this block and check is compreset packages apear in this folder.
delete .rar's and butterfly and butterfly_grasshopper folder. unload grasshopper. load grasshopper and run this block again.）

**Comment by mostaphaRoudsari** [comment]
The error has nothing to do with Butterfly. You're using an older version of GHPython which doesn't have AdditionalHelpFromDocStrings method. What is the version of GHPython that you'r using?

Also [see this](http://discourse.ladybug.tools/t/ladybug-installation-problems/47/9).
