### ISSUE TITLE
WindowError win32 exception

### ISSUE THREAD

**Issue by audaich** [ladybug-tools/butterfly#382]
Butterfly is throwing an error at the block mesh stage after creating a case. Error seems to be with os.chdir but unsure. Screen shot attached for info. Any ideas here?

![capture](https://user-images.githubusercontent.com/48143327/53675944-db8cd180-3c50-11e9-8294-7b50d4d6792d.PNG)

**Comment by laurensversluis** [comment]
I am having the exact same error. Having both blueCFD (terminal) and Rhino6 running in admin mode.

**Comment by laurensversluis** [comment]
It seems this issue is related to hardcoded c drive for the user folder on line 46 in runmanager_bluecfd.py

**Comment by Tomalwo** [comment]
I get the same error, and have found out the following:

`os.getenv('USERNAME')`

 on line 46 in runmanager_bluecfd.py yields "Thomas", but the project folder is in "thomas_wortmann". 

I couldn't find where the project path with "thomas_wortmann" is created (It'd be helpful if someone could point that out). Possibly this issue is somehow related with updating from Windows 7 to Windows 10, and the associated changes in account management.

**Comment by totoroxuan** [comment]
solved, thx

**Comment by reka-btoth** [comment]
Hei, 
I am still having the WindowsError after doing the suggested changes in line 45 in runmanager_bluecfd.py (

Any tips?

![runmanager_prtscr_01](https://user-images.githubusercontent.com/51444539/128183861-eda939fb-f8c8-4e65-8875-0153fb17e4d6.JPG)

In the Users/ .. / butterfly/oudoorairflow/log folder I dont see any log. 

Reka

@mostaphaRoudsari , @Tomalwo

**Comment by Hueherve** [comment]
Hi, 

SOLVED BY INSTALLING BLUE CFD CORE 2017-2 instead of 2020-1 ... Ridiculous ... How to understand these things.. Anyways...

Help please someone. I spent hours trying to fix this issue. I tried modifying the line 45 as @Tomalwo mentioned. I recently installed Rhino 7 and the most recent version of Butterfly. I ran everything as administrator, put Rhino in meters, cooked a soup for my grandma, everything... 

I have a different error after changing line 45 though, see attached. 

Thanks

![Rihno_butterfly_error_noob101](https://user-images.githubusercontent.com/55407260/154378275-6b1459df-c242-4510-a3ba-09bacd71f0e3.png)

**Comment by xuannfx** [comment]
I got a different error…
Any tips？
![image](https://user-images.githubusercontent.com/94786236/196051431-43b10cf5-95f7-4082-acbe-577c9f2e8771.png)

**Comment by TimidTiger** [comment]
still no workaround for this??!

**Comment by calvinlee6806** [comment]
> still no workaround for this??!

Agreed....How is everyone solving this problem? I also spent hours trying to solve this problem, uninstalled everything and then installed everything according to all forum manuals, and then run everything as administrator, and still failed.

![Image](https://github.com/user-attachments/assets/90f0c6f2-d4d2-4be3-9bc4-86cb21bc5f46)

**Comment by ymg2007** [comment]
You can try to run butterfly in Rhino7.
